# Generated by Django 4.2.7 on 2023-11-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Garantia',
            fields=[
                ('id_garantia', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vencimiento', models.PositiveIntegerField(max_length=10)),
                ('codigo_garantia', models.PositiveIntegerField(max_length=6)),
                ('detalles_garantia', models.CharField(max_length=100)),
                ('detalles_vehiculo', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='EstadosGarantia',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('estado_finalizado', models.CharField(max_length=15)),
                ('estado_creado', models.CharField(max_length=15)),
                ('id_garantia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indexg.garantia')),
            ],
        ),
    ]
