# Generated by Django 4.2.7 on 2023-11-08 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estadosgarantia',
            options={'ordering': ['id_estado'], 'verbose_name': 'warrantyState', 'verbose_name_plural': 'estadosGarantia'},
        ),
        migrations.AlterModelOptions(
            name='garantia',
            options={'ordering': ['id_garantia'], 'verbose_name': 'Warranty', 'verbose_name_plural': 'garantia'},
        ),
        migrations.RemoveField(
            model_name='estadosgarantia',
            name='estado_creado',
        ),
        migrations.RemoveField(
            model_name='estadosgarantia',
            name='estado_finalizado',
        ),
        migrations.RemoveField(
            model_name='estadosgarantia',
            name='id_garantia',
        ),
        migrations.RemoveField(
            model_name='garantia',
            name='fecha_vencimiento',
        ),
        migrations.AddField(
            model_name='estadosgarantia',
            name='estados',
            field=models.CharField(default=123, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='garantia',
            name='estados',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='indexg.estadosgarantia'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='garantia',
            name='codigo_garantia',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterModelTable(
            name='estadosgarantia',
            table='EstadosGarantia',
        ),
        migrations.AlterModelTable(
            name='garantia',
            table='Garantia',
        ),
    ]
