# Generated by Django 4.2.7 on 2023-11-08 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexg', '0002_alter_estadosgarantia_options_alter_garantia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='garantia',
            name='fecha_vencimiento',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
